reth_container_image: "ghcr.io/paradigmxyz/reth:nightly"
ethereum_node_cl_beacon_endpoint: "https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@bn.lighthouse-nethermind-1.{{ network_subdomain }}"
