# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora-endpoints-el.yaml.j2
# Execution layer endpoints

- url: http://geth-prysm-001:8545
  name: rpc-prysm-geth-001
  authGroup: pandaops
  archive: true
  priority: 1
- url: https://rpc.bootnode-1.perf-devnet-3.ethpandaops.io
  name: bootnode-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc.bootnode-1.perf-devnet-3.ethpandaops.io:8961
- url: https://rpc.lighthouse-geth-1.perf-devnet-3.ethpandaops.io
  name: lighthouse-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc.lighthouse-geth-1.perf-devnet-3.ethpandaops.io:8961
- url: https://rpc.lighthouse-nethermind-1.perf-devnet-3.ethpandaops.io
  name: lighthouse-nethermind-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc.lighthouse-nethermind-1.perf-devnet-3.ethpandaops.io:8961
- url: https://rpc.lighthouse-reth-1.perf-devnet-3.ethpandaops.io
  name: lighthouse-reth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc.lighthouse-reth-1.perf-devnet-3.ethpandaops.io:8961
- url: https://rpc.nimbus-besu-1.perf-devnet-3.ethpandaops.io
  name: nimbus-besu-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc.nimbus-besu-1.perf-devnet-3.ethpandaops.io:8961
- url: https://rpc.prysm-geth-1.perf-devnet-3.ethpandaops.io
  name: prysm-geth-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc.prysm-geth-1.perf-devnet-3.ethpandaops.io:8961
- url: https://rpc.teku-erigon-1.perf-devnet-3.ethpandaops.io
  name: teku-erigon-1
  authGroup: pandaops
  priority: -1
  archive: false
  engineSnooperUrl: http://rpc.teku-erigon-1.perf-devnet-3.ethpandaops.io:8961
