# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/dora
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1500m
      memory: 3Gi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.0.js" integrity="sha384-j6D+DanVUQs7XYmJaMXGwg2VdBq07F/ekc+bP5CNPsLOYCv4TKf8r3JBWqxwakKL" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: dora.perf-devnet-2.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  name: perf-devnet-2
  configPath: "https://config.perf-devnet-2.ethpandaops.io/cl/config.yaml"
  validatorNamesInventory: "https://config.perf-devnet-2.ethpandaops.io/api/v1/nodes/validator-ranges"
  ethExplorerLink: "https://explorer.perf-devnet-2.ethpandaops.io"
  publicRpcUrl: "https://rpc.perf-devnet-2.ethpandaops.io"
  rainbowkitProjectId: "15fe4ab4d5c0bcb6f0dc7c398301ff0e"
  executionGenesisConfig: "https://config.perf-devnet-2.ethpandaops.io/el/genesis.json"
  apiRequireAuth: False
  apiAuthSecret: "<path:/secrets/services/services.enc.yaml#dora | jsonPath {.api_secret}>"
  apiWhitelistedIPs: []
  apiDefaultRateLimit: 60
  apiDisableDefaultRateLimit: false
  proxyCount: 2
  executionIndexerEnabled: True
  executionIndexerRetention: 336h
  tracoorUrl: "https://tracoor.perf-devnet-2.ethpandaops.io"
  tracoorNetwork: "perf-devnet-2"

  
  extraEnv:
    - name: FRONTEND_PPROF
      value: "true"
    - name: FRONTEND_SHOW_SENSITIVE_PEER_INFOS
      value: "true"
    - name: API_CORS_ORIGINS
      value: "*"
    - name: FRONTEND_ENABLE_DAS_GUARDIAN_MASS_SCAN
      value: "true"
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
    persistence:
      size: "50Gi"

  mevRelays:
    - index: 0
      name: "Flashbots"
      url: "http://mev-relay-1.perf-devnet-2.ethpandaops.io:9062/"

  authGroups:
    pandaops:
      credentials:
        username: ""
        password: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>"

  endpointsUrl: "https://raw.githubusercontent.com/ethpandaops/perf-devnets/refs/heads/master/kubernetes/devnet-2/dora/endpoints-cl.yaml"
  executionEndpointsUrl: "https://raw.githubusercontent.com/ethpandaops/perf-devnets/refs/heads/master/kubernetes/devnet-2/dora/endpoints-el.yaml"
