# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

prysm-geth-001:
  global:
    main:
      network: perf-devnet-2
      engineEndpoint: http://geth-prysm-001:8551
      rpcEndpoint: http://geth-prysm-001:8545
      beaconEndpoint: http://prysm-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        perf-devnet-2: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.perf-devnet-2.ethpandaops.io
    clientArgs:
      networks:
        perf-devnet-2:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://22c1dd13d7738ae461740bbe1340733bdabe88c0682b5788bb308bb80f0d6281085196600416f187dc0f1d5d9613b1c2590e6e5b4003329a464910f613bd096a@157.180.14.229:30303?discport=30303,enode://392ad17daab7575c42ba7229ff9f37def104e140b1a030cd33414897f76d8fbf43755d0a9834a30210460d9b69cc318958986782a60915497a9d337dda753d0c@206.189.58.47:30303?discport=30303,enode://6867a722d721cc444ae26f58d896844694264f7532b409f1d31797e77c5603728cc834b46b1e8f0d8dcd734e50280dc711cfab8c5fc5211430894c5fbcf0a86e@157.180.14.225:30303?discport=30303,enode://3ba5f46aa1a9d863de4ce5ff67ec46704c43b2a1d5100e272dbfec5e56b350113018d3e67c400f09db60d4ec55df025bd209802c67826717a33a48acbe13b305@157.180.14.226:30303?discport=30303,enode://292d8de2de3977c2a4c136a66e81da3896cea872a3b95451d4aa1737654e39dfea0ff1d060a0fba780d7bb7b16518202d0609a2756775bc633d0d5d95d5f6bb3@135.125.119.2:60303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --version-compatibility-protection=false
              - --target-gas-limit=1000000000
              - --sync-mode=SNAP
              - --sync-min-peers=1
              - --static-nodes-file=/data/network-config/static-nodes.json
              - --bonsai-limit-trie-logs-enabled=false
              - --network-id=12159
              - --cache-last-block-headers-preload-enabled=true
              - --cache-last-block-headers=15000
              - --Xplugin-rocksdb-high-spec-enabled=true
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --config=mainnet.cfg
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://22c1dd13d7738ae461740bbe1340733bdabe88c0682b5788bb308bb80f0d6281085196600416f187dc0f1d5d9613b1c2590e6e5b4003329a464910f613bd096a@157.180.14.229:30303?discport=30303,enode://392ad17daab7575c42ba7229ff9f37def104e140b1a030cd33414897f76d8fbf43755d0a9834a30210460d9b69cc318958986782a60915497a9d337dda753d0c@206.189.58.47:30303?discport=30303,enode://6867a722d721cc444ae26f58d896844694264f7532b409f1d31797e77c5603728cc834b46b1e8f0d8dcd734e50280dc711cfab8c5fc5211430894c5fbcf0a86e@157.180.14.225:30303?discport=30303,enode://3ba5f46aa1a9d863de4ce5ff67ec46704c43b2a1d5100e272dbfec5e56b350113018d3e67c400f09db60d4ec55df025bd209802c67826717a33a48acbe13b305@157.180.14.226:30303?discport=30303,enode://292d8de2de3977c2a4c136a66e81da3896cea872a3b95451d4aa1737654e39dfea0ff1d060a0fba780d7bb7b16518202d0609a2756775bc633d0d5d95d5f6bb3@135.125.119.2:60303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --Seq.MinLevel=Info
              - --Seq.ServerUrl=https://seq.nethermind.io
              - --Seq.ApiKey=yuOqjKOHhZCw2D2U7pmL
              - --Metrics.PushGatewayUrl=http://94.237.52.161:9000/metrics/nethermind-iudiy4raagaizaih1phuaShekighoJ2ixaecahvii7ohte3oozeeh0eTh7Aich1Shee9ceetuy3iGhexoh5naithoot8rebi7fee
              - --Blocks.TargetBlockGasLimit=1000000000
              - --TxPool.Size=10000
              - --log=INFO
              - --Init.NetworkId=12159
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --bootnodes=enode://22c1dd13d7738ae461740bbe1340733bdabe88c0682b5788bb308bb80f0d6281085196600416f187dc0f1d5d9613b1c2590e6e5b4003329a464910f613bd096a@157.180.14.229:30303?discport=30303,enode://392ad17daab7575c42ba7229ff9f37def104e140b1a030cd33414897f76d8fbf43755d0a9834a30210460d9b69cc318958986782a60915497a9d337dda753d0c@206.189.58.47:30303?discport=30303,enode://6867a722d721cc444ae26f58d896844694264f7532b409f1d31797e77c5603728cc834b46b1e8f0d8dcd734e50280dc711cfab8c5fc5211430894c5fbcf0a86e@157.180.14.225:30303?discport=30303,enode://3ba5f46aa1a9d863de4ce5ff67ec46704c43b2a1d5100e272dbfec5e56b350113018d3e67c400f09db60d4ec55df025bd209802c67826717a33a48acbe13b305@157.180.14.226:30303?discport=30303,enode://292d8de2de3977c2a4c136a66e81da3896cea872a3b95451d4aa1737654e39dfea0ff1d060a0fba780d7bb7b16518202d0609a2756775bc633d0d5d95d5f6bb3@135.125.119.2:60303
              - --cache=4096
              - --miner.gaslimit=1000000000
              - --txpool.globalqueue=10000
              - --txpool.globalslots=10000
              - --networkid=12159
              - --override.osaka=1864841831
              - --override.bpo1=1864841831
              - --override.bpo2=1864841831
              - --rpc.allow-unprotected-txs
            erigon:
              - --http.api=eth,erigon,engine,web3,net,debug,trace,txpool,admin
              - --http.vhosts=*
              - --ws
              - --prune.mode=full
              - --chain=bloatnet
              - --trustedpeers=enode://22c1dd13d7738ae461740bbe1340733bdabe88c0682b5788bb308bb80f0d6281085196600416f187dc0f1d5d9613b1c2590e6e5b4003329a464910f613bd096a@157.180.14.229:30303?discport=30303,enode://392ad17daab7575c42ba7229ff9f37def104e140b1a030cd33414897f76d8fbf43755d0a9834a30210460d9b69cc318958986782a60915497a9d337dda753d0c@206.189.58.47:30303?discport=30303,enode://6867a722d721cc444ae26f58d896844694264f7532b409f1d31797e77c5603728cc834b46b1e8f0d8dcd734e50280dc711cfab8c5fc5211430894c5fbcf0a86e@157.180.14.225:30303?discport=30303,enode://3ba5f46aa1a9d863de4ce5ff67ec46704c43b2a1d5100e272dbfec5e56b350113018d3e67c400f09db60d4ec55df025bd209802c67826717a33a48acbe13b305@157.180.14.226:30303?discport=30303,enode://292d8de2de3977c2a4c136a66e81da3896cea872a3b95451d4aa1737654e39dfea0ff1d060a0fba780d7bb7b16518202d0609a2756775bc633d0d5d95d5f6bb3@135.125.119.2:60303
              - --externalcl
              - --miner.gaslimit=1000000000
              - --txpool.globalslots=10000
              - --log.console.verbosity=info
              - --log.dir.verbosity=debug
              - --pprof
              - --pprof.addr=0.0.0.0
              - --pprof.port=6060
              - --torrent.download.rate=1gb
            ethereumjs:
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QO5d3m9DzBlj1PLCovLotwN8b9mFp_MrCx-KiNjzltphcYYT7oeD-VU7qyuNJd50X3wlJwjd6C989B3DkVcQ3tiGAZfpKz9kgmlkgnY0gmlwhJ20DuWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-L64QCB2z4aZzDBXQMCZTdS_B5CYRIPffXvWxFOhvw_WnKXaMowcNKJTZbfkmdVlYYUZj01kpFY7okHgAtoKAE9ZWkSCAbSHYXR0bmV0c4gAAAAAAAYAAIRldGgykEDDUllggCdk__________-CaWSCdjSCaXCEnbQO5YlzZWNwMjU2azGhAkyk6UcdkGDO0CkITaYTj8xlGqACLZjzW7jjo04XtETTiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo,enr:-Mq4QOCWWhe9dWcrWdECv5AyOqVKbaEfVr88chEqJZwBEGKhIFdV2iaRHMsbLEjwWfD4YeL7XJYc5bnAuK_vENW_K3WGAZxEmoQSh2F0dG5ldHOIAAAAABgAAACEZXRoMpBAw1JZcAAAAP__________gmlkgnY0gmlwhJ20DuGEcXVpY4IyyIlzZWNwMjU2azGhAxGubm7aAy74-bdXgmWuqhv7PKcDS40k_aaU5Ece-9NpiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
              - --chain.persistInvalidSszObjects=true
            teku:
              - --network=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QO5d3m9DzBlj1PLCovLotwN8b9mFp_MrCx-KiNjzltphcYYT7oeD-VU7qyuNJd50X3wlJwjd6C989B3DkVcQ3tiGAZfpKz9kgmlkgnY0gmlwhJ20DuWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-L64QCB2z4aZzDBXQMCZTdS_B5CYRIPffXvWxFOhvw_WnKXaMowcNKJTZbfkmdVlYYUZj01kpFY7okHgAtoKAE9ZWkSCAbSHYXR0bmV0c4gAAAAAAAYAAIRldGgykEDDUllggCdk__________-CaWSCdjSCaXCEnbQO5YlzZWNwMjU2azGhAkyk6UcdkGDO0CkITaYTj8xlGqACLZjzW7jjo04XtETTiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo,enr:-Mq4QOCWWhe9dWcrWdECv5AyOqVKbaEfVr88chEqJZwBEGKhIFdV2iaRHMsbLEjwWfD4YeL7XJYc5bnAuK_vENW_K3WGAZxEmoQSh2F0dG5ldHOIAAAAABgAAACEZXRoMpBAw1JZcAAAAP__________gmlkgnY0gmlwhJ20DuGEcXVpY4IyyIlzZWNwMjU2azGhAxGubm7aAy74-bdXgmWuqhv7PKcDS40k_aaU5Ece-9NpiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --p2p-peer-upper-bound=100
              - --data-storage-non-canonical-blocks-enabled=true
              - --data-storage-mode=PRUNE
              - --logging=info
              - --Xlog-include-p2p-warnings-enabled
              - --metrics-block-timing-tracking-enabled
              - --ignore-weak-subjectivity-period-enabled
              - --rest-api-docs-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --save-invalid-block-temp
              - --save-invalid-blob-temp
              - --bootstrap-node=enr:-Iq4QO5d3m9DzBlj1PLCovLotwN8b9mFp_MrCx-KiNjzltphcYYT7oeD-VU7qyuNJd50X3wlJwjd6C989B3DkVcQ3tiGAZfpKz9kgmlkgnY0gmlwhJ20DuWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-L64QCB2z4aZzDBXQMCZTdS_B5CYRIPffXvWxFOhvw_WnKXaMowcNKJTZbfkmdVlYYUZj01kpFY7okHgAtoKAE9ZWkSCAbSHYXR0bmV0c4gAAAAAAAYAAIRldGgykEDDUllggCdk__________-CaWSCdjSCaXCEnbQO5YlzZWNwMjU2azGhAkyk6UcdkGDO0CkITaYTj8xlGqACLZjzW7jjo04XtETTiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-Mq4QOCWWhe9dWcrWdECv5AyOqVKbaEfVr88chEqJZwBEGKhIFdV2iaRHMsbLEjwWfD4YeL7XJYc5bnAuK_vENW_K3WGAZxEmoQSh2F0dG5ldHOIAAAAABgAAACEZXRoMpBAw1JZcAAAAP__________gmlkgnY0gmlwhJ20DuGEcXVpY4IyyIlzZWNwMjU2azGhAxGubm7aAy74-bdXgmWuqhv7PKcDS40k_aaU5Ece-9NpiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QO5d3m9DzBlj1PLCovLotwN8b9mFp_MrCx-KiNjzltphcYYT7oeD-VU7qyuNJd50X3wlJwjd6C989B3DkVcQ3tiGAZfpKz9kgmlkgnY0gmlwhJ20DuWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI,enr:-L64QCB2z4aZzDBXQMCZTdS_B5CYRIPffXvWxFOhvw_WnKXaMowcNKJTZbfkmdVlYYUZj01kpFY7okHgAtoKAE9ZWkSCAbSHYXR0bmV0c4gAAAAAAAYAAIRldGgykEDDUllggCdk__________-CaWSCdjSCaXCEnbQO5YlzZWNwMjU2azGhAkyk6UcdkGDO0CkITaYTj8xlGqACLZjzW7jjo04XtETTiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo,enr:-Mq4QOCWWhe9dWcrWdECv5AyOqVKbaEfVr88chEqJZwBEGKhIFdV2iaRHMsbLEjwWfD4YeL7XJYc5bnAuK_vENW_K3WGAZxEmoQSh2F0dG5ldHOIAAAAABgAAACEZXRoMpBAw1JZcAAAAP__________gmlkgnY0gmlwhJ20DuGEcXVpY4IyyIlzZWNwMjU2azGhAxGubm7aAy74-bdXgmWuqhv7PKcDS40k_aaU5Ece-9NpiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --invalid-gossip-verified-blocks-path=/data/lighthouse/invalid
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG
              - --light-client-data-serve=false
              - --dump
              - --bootstrap-node=enr:-Iq4QO5d3m9DzBlj1PLCovLotwN8b9mFp_MrCx-KiNjzltphcYYT7oeD-VU7qyuNJd50X3wlJwjd6C989B3DkVcQ3tiGAZfpKz9kgmlkgnY0gmlwhJ20DuWJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIzI
              - --bootstrap-node=enr:-L64QCB2z4aZzDBXQMCZTdS_B5CYRIPffXvWxFOhvw_WnKXaMowcNKJTZbfkmdVlYYUZj01kpFY7okHgAtoKAE9ZWkSCAbSHYXR0bmV0c4gAAAAAAAYAAIRldGgykEDDUllggCdk__________-CaWSCdjSCaXCEnbQO5YlzZWNwMjU2azGhAkyk6UcdkGDO0CkITaYTj8xlGqACLZjzW7jjo04XtETTiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo
              - --bootstrap-node=enr:-Mq4QOCWWhe9dWcrWdECv5AyOqVKbaEfVr88chEqJZwBEGKhIFdV2iaRHMsbLEjwWfD4YeL7XJYc5bnAuK_vENW_K3WGAZxEmoQSh2F0dG5ldHOIAAAAABgAAACEZXRoMpBAw1JZcAAAAP__________gmlkgnY0gmlwhJ20DuGEcXVpY4IyyIlzZWNwMjU2azGhAxGubm7aAy74-bdXgmWuqhv7PKcDS40k_aaU5Ece-9NpiHN5bmNuZXRzAIN0Y3CCIyiDdWRwgiMo


  geth:
    enabled: true
    fullnameOverride: geth-prysm-001
    image:
      repository: docker.ethquokkaops.io/dh/ethpandaops/geth
      tag: master
      pullPolicy: Always
    p2pNodePort:
      enabled: true
      port: 31686
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: perf-devnet-2
      testnet: perf-devnet-2
      ethereum_network: perf-devnet-2
      ethereum_role: execution
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: geth-prysm-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.perf-devnet-2.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.perf-devnet-2.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.perf-devnet-2.ethpandaops.io/el/besu.json;
            ENODES_URI=https://config.perf-devnet-2.ethpandaops.io/el/enodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/enodes.txt $ENODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/enodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: docker.ethquokkaops.io/dh/ethpandaops/geth:master
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  prysm:
    checkpointSync:
      enabled: false
      addresses:
        perf-devnet-2: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.perf-devnet-2.ethpandaops.io
    enabled: true
    fullnameOverride: prysm-geth-001
    image:
      repository: docker.ethquokkaops.io/gcr/prysmaticlabs/prysm/beacon-chain
      tag: latest
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: true
      port: 32686
    podLabels:
      network: perf-devnet-2
      testnet: perf-devnet-2
      ethereum_network: perf-devnet-2
      ethereum_role: consensus
      consensus_client: prysm
      execution_client: geth
      ethereum_instance: prysm-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.perf-devnet-2.ethpandaops.io/cl/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.perf-devnet-2.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPOSIT_CONTRACT_BLOCK_HASH_URI=https://config.perf-devnet-2.ethpandaops.io/cl/deposit_contract_block_hash.txt;
          GENESIS_CONFIG_URI=https://config.perf-devnet-2.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.perf-devnet-2.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.perf-devnet-2.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootstrap_nodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deposit_contract_block_hash.txt $DEPOSIT_CONTRACT_BLOCK_HASH_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootstrap_nodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootstrap_nodes2.txt;
          mv /data/network-config/bootstrap_nodes2.txt /data/network-config/bootstrap_nodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootstrap_nodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
