# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/assertoor.yaml.j2

assertoor:
  fullnameOverride: assertoor

  image:
    repository: docker.ethquokkaops.io/dh/ethpandaops/assertoor
    tag: master-latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 2000m
      memory: 2Gi

  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        sub_filter '</head>' '<script src="https://pandamenu.ethpandaops.io/panda-menu-1.0.0.js" integrity="sha384-j6D+DanVUQs7XYmJaMXGwg2VdBq07F/ekc+bP5CNPsLOYCv4TKf8r3JBWqxwakKL" crossorigin="anonymous"></script></head>';
        sub_filter_types text/html;
        sub_filter_once off;
    hosts:
      - host: assertoor.perf-devnet-3.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  ingressAdmin:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: assertoor-admin.perf-devnet-3.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

  persistence:
    enabled: true

  endpoints:
    - name:  bootnode-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@rpc.bootnode-1.perf-devnet-3.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@bn.bootnode-1.perf-devnet-3.ethpandaops.io
    - name:  lighthouse-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@rpc.lighthouse-geth-1.perf-devnet-3.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.perf-devnet-3.ethpandaops.io
    - name:  lighthouse-nethermind-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@rpc.lighthouse-nethermind-1.perf-devnet-3.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@bn.lighthouse-nethermind-1.perf-devnet-3.ethpandaops.io
    - name:  lighthouse-reth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@rpc.lighthouse-reth-1.perf-devnet-3.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@bn.lighthouse-reth-1.perf-devnet-3.ethpandaops.io
    - name:  nimbus-besu-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@rpc.nimbus-besu-1.perf-devnet-3.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@bn.nimbus-besu-1.perf-devnet-3.ethpandaops.io
    - name:  prysm-geth-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@rpc.prysm-geth-1.perf-devnet-3.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@bn.prysm-geth-1.perf-devnet-3.ethpandaops.io
    - name:  teku-erigon-1
      executionUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@rpc.teku-erigon-1.perf-devnet-3.ethpandaops.io
      consensusUrl: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.node_ingress.combined}>@bn.teku-erigon-1.perf-devnet-3.ethpandaops.io

  validatorNamesInventory: https://config.perf-devnet-3.ethpandaops.io/api/v1/nodes/validator-ranges
  globalVariables:
    walletPrivkey: "<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.perf-devnets.assertoor_private_key}>"
    clientPairNames:
      - bootnode-1
      - lighthouse-geth-1
      - lighthouse-nethermind-1
      - lighthouse-reth-1
      - nimbus-besu-1
      - prysm-geth-1
      - teku-erigon-1
    validatorPairNames:
      - prysm-geth-1

  assertoorTests: []